# Use an official Apache image as the base image
FROM httpd:2.4

# Copy your custom configuration file if needed
# COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf

# Copy the index.html file to the document root
COPY ./index.html /usr/local/apache2/htdocs/
COPY ./style.css /usr/local/apache2/htdocs/
COPY ./img1.jpg /usr/local/apache2/htdocs/
COPY ./logoText.PNG /usr/local/apache2/htdocs/
COPY ./card1.jpg /usr/local/apache2/htdocs/
COPY ./card2.jpg /usr/local/apache2/htdocs/
COPY ./card3.jpg /usr/local/apache2/htdocs/
COPY ./card4.jpg /usr/local/apache2/htdocs/
COPY ./arrowIcon.png /usr/local/apache2/htdocs/
COPY ./skyscrapers.jpeg /usr/local/apache2/htdocs/
COPY ./favicon.ico /usr/local/apache2/htdocs/
COPY ./script.js /usr/local/apache2/htdocs/


